name: On Tag
on:
  push:
    tags:
    - "v*"

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: acorn-io/actions-setup@v1
    - uses: acorn-io/actions-login@v1
      with:
        registry: docker.io
        username: dbodky
        password: ${{ secrets.DOCKER_PAT }} 
    - name: Set Tag
      run: |
        echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and Push
      run: |
        acorn build --tag index.docker.io/dbodky/acorn-icinga2:$TAG .
        acorn push index.docker.io/dbodky/acorn-icinga2:$TAG
